default: &default
  adapter: postgresql
  encoding: unicode

# production:
  # url: <%= ENV["DATABASE_URL_PRODUCTION"] %>

production:
 <<: *default
  database: clinic
  username: clinic
  password: <%= ENV["CLINIC_DATABASE_PASSWORD"] %>

development:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?' ) %>
test:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?' ) %>
